services:
  backend:
    build: ./reservations-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    build: 
      context: ./reservations-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./reservations-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: reservations
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin123
    depends_on:
      - db