export enum NotificationType {
  RESERVATION_CREATED = 'RESERVATION_CREATED',
  RESERVATION_CONFIRMED = 'RESERVATION_CONFIRMED',
  RESERVATION_REJECTED = 'RESERVATION_REJECTED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  RESERVATION_COMPLETED = 'RESERVATION_COMPLETED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  SYSTEM = 'SYSTEM'
}