services:
  # Database Services
  mysql-db:
    image: mysql:8.0
    container_name: reservations-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: reservations-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: reservations-api-gateway
    restart: unless-stopped
    ports:
      - "${API_GATEWAY_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - HOTEL_SERVICE_URL=${HOTEL_SERVICE_URL}
      - RESERVATION_SERVICE_URL=${RESERVATION_SERVICE_URL}
      - SEARCH_SERVICE_URL=${SEARCH_SERVICE_URL}
      - AVAILABILITY_SERVICE_URL=${AVAILABILITY_SERVICE_URL}
      - REVIEW_SERVICE_URL=${REVIEW_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL}
      - REPORT_SERVICE_URL=${REPORT_SERVICE_URL}
    depends_on:
      auth-service:
        condition: service_healthy
      hotel-service:
        condition: service_healthy
      reservation-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
      review-service:
        condition: service_healthy
      report-service:
        condition: service_healthy
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      timeout: 10s
      retries: 5

  # Authentication Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: reservations-auth-service
    restart: unless-stopped
    ports:
      - "${AUTH_SERVICE_PORT}:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      timeout: 10s
      retries: 5

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: reservations-user-service
    restart: unless-stopped
    ports:
      - "${USER_SERVICE_PORT}:3002"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      timeout: 10s
      retries: 5

  # Hotel Service
  hotel-service:
    build:
      context: ./hotel-service
      dockerfile: Dockerfile
    container_name: reservations-hotel-service
    restart: unless-stopped
    ports:
      - "${HOTEL_SERVICE_PORT}:3003"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      timeout: 10s
      retries: 5

  # Reservation Service
  reservation-service:
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    container_name: reservations-reservation-service
    restart: unless-stopped
    ports:
      - "${RESERVATION_SERVICE_PORT}:3004"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      timeout: 10s
      retries: 5

  # Review Service
  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    container_name: reservations-review-service
    restart: unless-stopped
    ports:
      - "${REVIEW_SERVICE_PORT}:3005"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      timeout: 10s
      retries: 5

  # Notification Service
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: reservations-notification-service
    restart: unless-stopped
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:3006"
    environment:
      - NODE_ENV=${NODE_ENV}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      timeout: 10s
      retries: 5

  # Report Service
  report-service:
    build:
      context: ./report-service
      dockerfile: Dockerfile
    container_name: reservations-report-service
    restart: unless-stopped
    ports:
      - "${REPORT_SERVICE_PORT}:3007"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/health"]
      timeout: 10s
      retries: 5

  # Payment Service
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: reservations-payment-service
    restart: unless-stopped
    ports:
      - "${PAYMENT_SERVICE_PORT}:3008"
    environment:
      - NODE_ENV=${NODE_ENV}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - PAYMENT_CURRENCY=${PAYMENT_CURRENCY}
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3008/health"]
      timeout: 10s
      retries: 5

  # Availability Service
  availability-service:
    build:
      context: ./availability-service
      dockerfile: Dockerfile
    container_name: reservations-availability-service
    restart: unless-stopped
    ports:
      - "${AVAILABILITY_SERVICE_PORT}:3009"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/health"]
      timeout: 10s
      retries: 5

  # Search Service
  search-service:
    build:
      context: ./search-service
      dockerfile: Dockerfile
    container_name: reservations-search-service
    restart: unless-stopped
    ports:
      - "${SEARCH_SERVICE_PORT}:3010"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - reservations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/health"]
      timeout: 10s
      retries: 5

volumes:
  mysql_data:

networks:
  reservations-network:
    driver: bridge